[package]
authors = ["mmacedoeu <contato@mmacedo.eu.org>"]
name = "fconfig"
version = "0.1.0"
[dependencies]
config = "0.9.0"
failure = "0.1.2"
serde = "^1.0"
serde_derive = "^1.0"

[dependencies.app-dir]
path = "../app-dir"
